# Generated by Django 4.2.4 on 2023-09-02 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prep', models.CharField(default='', max_length=50)),
                ('frequency', models.IntegerField(default=1)),
                ('banned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KillVerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zu', models.CharField(default='zu töten', max_length=200)),
                ('ge', models.CharField(default='getötet', max_length=200)),
                ('imp', models.CharField(default='töte', max_length=200)),
                ('frequency', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PendingBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(default='Keine Begründung.')),
                ('pro', models.IntegerField(default=0)),
                ('con', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_valid', models.BooleanField(default=False)),
                ('distance', models.IntegerField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.item')),
            ],
        ),
    ]
