# Generated by Django 4.2.4 on 2023-09-02 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='killer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='killer_quests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quest',
            name='verb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='state.killverb'),
        ),
        migrations.AddField(
            model_name='quest',
            name='victim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_quests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingban',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.item'),
        ),
        migrations.AddField(
            model_name='pendingban',
            name='users_voted',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
