# Generated by Django 4.2.4 on 2023-08-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prep',
            field=models.CharField(default='', max_length=50),
        ),
    ]
