# Generated by Django 4.2.4 on 2023-08-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_item_prep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
