# Generated by Django 4.2.4 on 2023-09-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_alter_item_prep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='pending_valid',
        ),
        migrations.AddField(
            model_name='quest',
            name='state',
            field=models.CharField(default='unopened', max_length=50),
        ),
    ]
