# Generated by Django 4.2.4 on 2023-08-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_alter_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingban',
            name='ntr',
        ),
        migrations.RemoveField(
            model_name='pendingban',
            name='voted',
        ),
        migrations.AddField(
            model_name='quest',
            name='await_valid',
            field=models.BooleanField(default=False),
        ),
    ]
