# Generated by Django 4.2.4 on 2023-09-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_remove_quest_pending_valid_quest_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='ban_state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pendingban',
            name='pro',
            field=models.IntegerField(default=1),
        ),
    ]
