# Generated by Django 4.2.4 on 2023-09-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0005_quest_ban_state_alter_pendingban_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='banned',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='ban_state',
        ),
        migrations.AddField(
            model_name='item',
            name='ban_state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
