# Generated by Django 4.2.4 on 2023-09-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0006_remove_item_banned_remove_quest_ban_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingban',
            old_name='pro',
            new_name='ban',
        ),
        migrations.RenameField(
            model_name='pendingban',
            old_name='con',
            new_name='keep',
        ),
        migrations.AlterField(
            model_name='item',
            name='ban_state',
            field=models.CharField(default='unbanned', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
