POST  http://127.0.0.1:8000/login/
Content-Type: application/json

{"username": "test4", "password": "123abc---"}

###

GET  http://127.0.0.1:8000/testtoken/
Content-Type: application/json
Authorization: Token 931ad6e8c143f008c80d0c2679649a06f6b9cb8d

{}

###

POST http://127.0.0.1:8000/state/newitem/
Content-Type: application/json
Authorization: Token 931ad6e8c143f008c80d0c2679649a06f6b9cb8d

{"prep": "einer ", "name": "gurke"}

###

GET http://127.0.0.1:8000/state/questdata/
Content-Type: application/json
Authorization: Token 931ad6e8c143f008c80d0c2679649a06f6b9cb8d

{}

###

GET http://127.0.0.1:8000/state/bandata/
Content-Type: application/json
Authorization: Token f6f2e776e2f0948b0e7bb2d16666a4616f278881

{}

###

GET http://127.0.0.1:8000/state/killvaldata/
Content-Type: application/json
Authorization: Token 931ad6e8c143f008c80d0c2679649a06f6b9cb8d

{}

###

GET http://127.0.0.1:8000/registry/unreadlogdata/
Content-Type: application/json
Authorization: Token 931ad6e8c143f008c80d0c2679649a06f6b9cb8d

{}

###

GET http://127.0.0.1:8000/state/requestkillval/
Content-Type: application/json
Authorization: Token 931ad6e8c143f008c80d0c2679649a06f6b9cb8d

{"quest_id": 3, "distance": 100}

###

GET http://127.0.0.1:8000/registry/statsdata/
Content-Type: application/json
Authorization: Token 931ad6e8c143f008c80d0c2679649a06f6b9cb8d

{}

###