# Generated by Django 4.2.4 on 2023-09-02 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prev_login',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 2, 11, 15, 40, 204927, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
