# Generated by Django 4.2.4 on 2023-08-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_auth', '0002_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notes',
        ),
        migrations.AddField(
            model_name='user',
            name='read_logs',
            field=models.JSONField(default='[]'),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_bans',
            field=models.JSONField(default='[]'),
        ),
    ]
