# Generated by Django 4.2.4 on 2023-08-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_auth', '0003_remove_user_notes_user_read_logs_user_voted_bans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='read_logs',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='voted_bans',
            field=models.JSONField(default=list),
        ),
    ]
