# Generated by Django 4.2.4 on 2023-09-02 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toast_auth', '0003_remove_user_prev_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prev_login',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
