# Generated by Django 4.2.4 on 2023-08-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_auth', '0004_alter_user_read_logs_alter_user_voted_bans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
