# Generated by Django 4.2.4 on 2023-09-02 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_auth', '0006_alter_user_prev_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prev_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 1, 0, 0)),
        ),
    ]
