# Generated by Django 4.2.4 on 2023-08-21 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_info', models.BooleanField(default=False)),
                ('info_title', models.CharField(default='', max_length=200)),
                ('info_text', models.TextField(default='')),
                ('item', models.CharField(default='', max_length=50)),
                ('killer', models.CharField(default='', max_length=50)),
                ('victim', models.CharField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=250)),
                ('success', models.BooleanField(default=False)),
                ('distance', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MsgTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=250)),
                ('for_success', models.BooleanField()),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('emote', models.CharField(max_length=1)),
                ('date', models.DateTimeField(auto_now=True)),
                ('on', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registry.blog')),
            ],
        ),
    ]
