# Generated by Django 4.2.4 on 2023-09-02 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='state.item'),
        ),
        migrations.AddField(
            model_name='comment',
            name='on',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registry.blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.log'),
        ),
    ]
