# Generated by Django 4.2.4 on 2023-09-02 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_initial'),
        ('registry', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='info_text',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='info_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='log',
            name='verb',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='state.killverb'),
            preserve_default=False,
        ),
    ]
