# Generated by Django 4.2.4 on 2023-09-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_rename_info_text_info_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
