# Generated by Django 4.2.4 on 2023-09-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_info_type_alter_blog_date_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
